# Generated by Django 3.1.3 on 2020-11-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='Images')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('songfile', models.FileField(upload_to='')),
            ],
        ),
    ]
