# Generated by Django 3.1.3 on 2020-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_image_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': ['id']},
        ),
        migrations.AlterField(
            model_name='image',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('en', 'English')], default=('en', 'English'), max_length=15),
        ),
    ]
