# Generated by Django 3.1.3 on 2020-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_auto_20201203_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='res_img',
            field=models.ImageField(default='./media/dummy.png', upload_to='res_img'),
        ),
    ]
