# Generated by Django 3.1.3 on 2020-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_image_res_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='res_img',
            field=models.ImageField(default='dummy.png', upload_to='res_img'),
        ),
    ]
