# Generated by Django 3.1.3 on 2020-12-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_auto_20201204_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploaded_pdfs')),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('en', 'English')], default=('en', 'English'), max_length=15)),
                ('img_folder', models.CharField(max_length=100)),
                ('img_pinter', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('songfile', models.FileField(upload_to='')),
            ],
        ),
    ]
