# Generated by Django 3.1.3 on 2020-12-10 09:57

import CoreApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0006_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='uploaded_pdfs', validators=[CoreApp.validators.validate_file_extension]),
        ),
    ]
